### ISSUE TITLE
Only English worlds in the topics

### ISSUE THREAD

**Issue by GoogleCodeExporter** [senderle/topic-modeling-tool#3] opened 2015-12-14 19:22 UTC
```
What steps will reproduce the problem?
1. Russian language texts with several english words in UTF-8 *.txt format as 
input.
2. There are only English words in the topics, without any russian one

What version of the product are you using? On what operating system?
I used the last version from the site on 32-bit Windows XP

I've attached the text files in the archieve


```

Original issue reported on code.google.com by `Semenoff...@gmail.com` on 25 Nov 2011 at 4:59

Attachments:
* [TXT.zip](https://storage.googleapis.com/google-code-attachments/topic-modeling-tool/issue-3/comment-0/TXT.zip)

**Comment by senderle** [comment] 2016-03-24 11:51
Based on the last comment, it appears this is an issue that will be dealt with when I add the token regex option (#8). Closing as a dupe of that issue.

**Closed by senderle** 2016-03-24 11:51 UTC
Labels: auto-migrated, duplicate, priority-medium
