### ISSUE TITLE
error running topic model gui

### ISSUE THREAD

**Issue by GoogleCodeExporter** [senderle/topic-modeling-tool#4] opened 2015-12-14 19:22 UTC
```

Total time: 0 seconds
java.lang.IndexOutOfBoundsException: Index: 284, Size: 10
at java.util.ArrayList.RangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at cc.mallet.topics.gui.HtmlBuilder.buildHtml2(HtmlBuilder.java:194)
at cc.mallet.topics.gui.HtmlBuilder.createHtmlFiles(HtmlBuilder.java:293)
at 
cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener.outputCsvFiles(TopicM
odelingTool.java:629)
at 
cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener.runMallet(TopicModeli
ngTool.java:581)
at 
cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener$1.run(TopicModelingTo
ol.java:446)
Mallet Output files written in C:\results ---> C:\results\output_state.gz , 
C:\results\output_topic_keys


Csv Output files written in C:\results\output_csv
Html Output files written in C:\results\output_html
```

Original issue reported on code.google.com by `gheg.ja...@gmail.com` on 29 Nov 2011 at 5:11

**Comment by senderle** [comment] 2016-03-24 11:49
This is troubling but since there's no information about how to replicate the problem, I'm closing this. If you're the original poster, give me an input file that reproduces this problem.

**Closed by senderle** 2016-03-24 11:49 UTC
Labels: auto-migrated, priority-medium
