### ISSUE TITLE
IndexOutOfBoundsExecption, no DocX.html files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [senderle/topic-modeling-tool#1] opened 2015-12-14 19:22 UTC
```
What steps will reproduce the problem?
1. Press 'Learn Topics' with file testdata_news_fuel_845docs.txt
2. standard options
3.

What is the expected output? What do you see instead?
The OutputHTML\Docs\DocX.html are not created. And in Topicindocs.csv file 
value for filename=null-source.

Error msg:
java.lang.IndexOutOfBoundsException: Index: 369, Size: 10
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at cc.mallet.topics.gui.HtmlBuilder.buildHtml2(HtmlBuilder.java:194)
	at cc.mallet.topics.gui.HtmlBuilder.createHtmlFiles(HtmlBuilder.java:293)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener.outputCsvFiles(TopicModelingTool.java:629)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener.runMallet(TopicModelingTool.java:581)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener$1.run(TopicModelingTool.java:446)
Mallet Output files written in C:\TopicModelingTool ---> 
C:\TopicModelingTool\output_state.gz , C:\TopicModelingTool\output_topic_keys

What version of the product are you using? On what operating system?
Topic modeling tool: Releasedate 3 oct. Windows 7 Home Premium SP1

Please provide any additional information below.


```

Original issue reported on code.google.com by `onno.nie...@gmail.com` on 22 Nov 2011 at 12:18

**Comment by senderle** [comment] 2016-03-24 11:54
Confirming that this data file still causes (different) problems. This really might be a new issue now, but I'm leaving it here for the time being. The test file is attached: [testdata_news_fuel_845docs.txt](https://github.com/senderle/topic-modeling-tool/files/187710/testdata_news_fuel_845docs.txt)

```
java.lang.IllegalArgumentException: URI is not absolute
	at java.io.File.<init>(File.java:416)
	at cc.mallet.topics.gui.CsvBuilder.extractFileSubstring(CsvBuilder.java:98)
	at cc.mallet.topics.gui.CsvBuilder.dtLine2Csv(CsvBuilder.java:118)
	at cc.mallet.topics.gui.CsvBuilder.topicsDocs(CsvBuilder.java:248)
	at cc.mallet.topics.gui.CsvBuilder.createCsvFiles(CsvBuilder.java:387)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener.outputCsvFiles(TopicModelingTool.java:502)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener.runMallet(TopicModelingTool.java:459)
	at cc.mallet.topics.gui.TopicModelingTool$TrainButtonListener$1.run(TopicModelingTool.java:326)
```

**Comment by senderle** [comment] 2016-03-27 23:11
This isn't currently an issue because I've disable single-file inputs. Reducing to low priority.

**Comment by senderle** [comment] 2016-03-27 23:21
Marking this as a dupe of #18.

**Closed by senderle** 2016-03-27 23:21 UTC
Labels: bug, migrated-and-vetted, priority-low
